DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS technicians;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id BIGINT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(25) NOT NULL,
  email VARCHAR(160) NOT NULL,
  address VARCHAR(160) NOT NULL,
  suburb VARCHAR(80) NOT NULL
);

CREATE TABLE technicians (
  id BIGINT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  initials VARCHAR(3) NOT NULL,
  specialty VARCHAR(120) NOT NULL,
  color VARCHAR(7) NOT NULL
);

CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  description VARCHAR(2000) NOT NULL,
  service_type VARCHAR(40) NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('scheduled', 'in-progress', 'completed', 'cancelled')),
  scheduled_date DATE NOT NULL,
  scheduled_time TIME NOT NULL,
  duration_minutes INTEGER NOT NULL CHECK (duration_minutes BETWEEN 15 AND 480),
  amount DECIMAL(10, 2) NOT NULL CHECK (amount BETWEEN 0 AND 100000),
  customer_id BIGINT NOT NULL REFERENCES customers(id),
  technician_id BIGINT NOT NULL REFERENCES technicians(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_jobs_schedule ON jobs(scheduled_date, scheduled_time);
CREATE INDEX idx_jobs_customer ON jobs(customer_id);
